# 퀴즈 1.

## 정답 확인 및 풀이 수정
-
---

### (1) < x, y > 재계산

$$\langle x, y \rangle = (1)(2) + (-1)(1) + (0)(1) + (2)(3) + (4)(0)$$

| 성분 | x | y | x×y |
|:---:|:---:|:---:|:---:|
| 1번째 | 1 | 2 | **2** |
| 2번째 | -1 | 1 | **-1** |
| 3번째 | 0 | 1 | **0** |
| 4번째 | 2 | 3 | **6** |
| 5번째 | 4 | 0 | **0** |

$$= 2 + (-1) + 0 + 6 + 0 = 7$$

---

### (2) ||x||

$$\|x\| = \sqrt{1^2 + (-1)^2 + 0^2 + 2^2 + 4^2} = \sqrt{1+1+0+4+16} = \sqrt{22}$$

---

### (3) ||y||

$$\|y\| = \sqrt{2^2 + 1^2 + 1^2 + 3^2 + 0^2} = \sqrt{4+1+1+9+0} = \sqrt{15}$$

---

## 최종 정답

$$\langle x,y \rangle = 7, \quad \|x\| = \sqrt{22}, \quad \|y\| = \sqrt{15}$$


In [ ]:
# 코드

(1) <x, y>  = 7
(2) ||x||   = √22 ≈ 4.6904
(3) ||y||   = √15 ≈ 3.8730


# 퀴즈 2.

## 문제

$v_1, v_2, w \in R^n$, $\langle v_1, w \rangle = 3$, $\langle v_2, w \rangle = -2$. Find $\langle 2v_1 - 3v_2, w \rangle$.

---

## 개념 정의 (p.32)

**내적의 선형성 (분배법칙)**

- $\langle v+u, w \rangle = \langle v,w \rangle + \langle u,w \rangle$
- $\langle \lambda v, w \rangle = \lambda \langle v,w \rangle$

---

## 풀이

(벡터의 선형 결합에 대한 내적의 분배법칙)

$$\langle 2v_1 - 3v_2, w \rangle = 2\langle v_1, w \rangle - 3\langle v_2, w \rangle = 2 \cdot 3 - 3 \cdot (-2) = 12$$

---

## 정답

$$\boxed{12}$$

In [ ]:
# 코드

<v1, w> = 3
<v2, w> = -2

<2v1 - 3v2, w> = 12
2<v1,w> - 3<v2,w> = 12


# 퀴즈 3.

## 문제

$$A = \begin{pmatrix} 3 & 1 \\ 2 & 1 \end{pmatrix} \begin{pmatrix} 1 & -1 \\ -2 & 3 \end{pmatrix}$$

---

## 개념 정의

**행렬의 곱셈**

$$A_{ij} = \sum_k B_{ik} C_{kj}$$

- 첫 번째 행렬의 $i$번째 행과 두 번째 행렬의 $j$번째 열의 내적을 계산

---

## 풀이

$$\begin{pmatrix} 3 & 1 \\ 2 & 1 \end{pmatrix} \begin{pmatrix} 1 & -1 \\ -2 & 3 \end{pmatrix} = \begin{pmatrix} (3\cdot1 + 1\cdot(-2)) & (3\cdot(-1) + 1\cdot3) \\ (2\cdot1 + 1\cdot(-2)) & (2\cdot(-1) + 1\cdot3) \end{pmatrix}$$

**첫 번째 행, 첫 번째 열:**
$$3\cdot1 + 1\cdot(-2) = 3 - 2 = 1$$

**첫 번째 행, 두 번째 열:**
$$3\cdot(-1) + 1\cdot3 = -3 + 3 = 0$$

**두 번째 행, 첫 번째 열:**
$$2\cdot1 + 1\cdot(-2) = 2 - 2 = 0$$

**두 번째 행, 두 번째 열:**
$$2\cdot(-1) + 1\cdot3 = -2 + 3 = 1$$

---

## 정답

$$\begin{pmatrix} 3 & 1 \\ 2 & 1 \end{pmatrix} \begin{pmatrix} 1 & -1 \\ -2 & 3 \end{pmatrix} = \boxed{\begin{pmatrix} 1 & 0 \\ 0 & 1 \end{pmatrix}}$$

In [ ]:
# 코드

A =
[[1 0]
 [0 1]]


# 퀴즈 4.

## 문제

$$A = \begin{pmatrix} -1 & 2 \\ -2 & 1 \\ 3 & 4 \end{pmatrix} \begin{pmatrix} 1 & 0 & 2 \\ 2 & -3 & 1 \end{pmatrix}$$

---

## 개념 정의

**행렬의 곱셈**

$$A_{ij} = \sum_k B_{ik} C_{kj}$$

- 왼쪽 행렬 $(3\times2)$ × 오른쪽 행렬 $(2\times3)$ → 결과 행렬 $(3\times3)$

---

## 풀이

$$\begin{pmatrix} -1 & 2 \\ -2 & 1 \\ 3 & 4 \end{pmatrix} \begin{pmatrix} 1 & 0 & 2 \\ 2 & -3 & 1 \end{pmatrix} = \begin{pmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{pmatrix}$$

**1행 1열:**
$$(-1)\cdot1 + 2\cdot2 = -1 + 4 = 3$$

**1행 2열:**
$$(-1)\cdot0 + 2\cdot(-3) = 0 - 6 = -6$$

**1행 3열:**
$$(-1)\cdot2 + 2\cdot1 = -2 + 2 = 0$$

**2행 1열:**
$$(-2)\cdot1 + 1\cdot2 = -2 + 2 = 0$$

**2행 2열:**
$$(-2)\cdot0 + 1\cdot(-3) = 0 - 3 = -3$$

**2행 3열:**
$$(-2)\cdot2 + 1\cdot1 = -4 + 1 = -3$$

**3행 1열:**
$$3\cdot1 + 4\cdot2 = 3 + 8 = 11$$

**3행 2열:**
$$3\cdot0 + 4\cdot(-3) = 0 - 12 = -12$$

**3행 3열:**
$$3\cdot2 + 4\cdot1 = 6 + 4 = 10$$

---

## 정답

$$\boxed{A = \begin{pmatrix} 3 & -6 & 0 \\ 0 & -3 & -3 \\ 11 & -12 & 10 \end{pmatrix}}$$

In [ ]:
# 코드

A =
[[  3  -6   0]
 [  0  -3  -3]
 [ 11 -12  10]]


---

## 핵심 포인트 요약

**행렬 곱셈 조건** — A가 m×r, B가 r×n일 때만 AB 가능, 결과는 m×n

**공식** — $(AB)_{ij} = \sum_k A_{ik} B_{kj}$

**주의사항 3가지**

- (1), (2)번 비교: $AB \neq BA$ → 행렬 곱셈은 **교환법칙 불성립**
- (3)번: 영행렬이 아닌 두 행렬의 곱이 **영행렬**이 될 수 있음
- (4)번: 두 행렬의 곱이 **단위행렬(I)**이 되면 서로 **역행렬** 관계

# 퀴즈 5.

## 문제

$$\begin{cases} x + 2y - 4z = 2 \\ x + 3y - 6z = 1 \\ x + 2y - 3z = 4 \end{cases}$$

---

## 개념 정의

### Gauss 소거법 (강의자료 49~50페이지)
- 첨가행렬을 **상삼각행렬** 형태로 변환
- 이후 **후진 대입법**으로 해를 구함
- 아래쪽 행의 계수만 0으로 만들면 됨

### Gauss-Jordan 소거법 (강의자료 54~55페이지)
- 첨가행렬을 **RREF(단위행렬)** 형태로 변환
- 후진 대입 없이 **해를 직접 읽어냄**
- 위아래 모든 행의 계수를 0으로 만들어야 함

---

## 방법 1: Gauss 소거법

### 첨가행렬 구성

$$\left[\begin{array}{ccc|c} 1 & 2 & -4 & 2 \\ 1 & 3 & -6 & 1 \\ 1 & 2 & -3 & 4 \end{array}\right]$$

---

### 1단계: $R_2 \leftarrow R_2 - R_1$, $R_3 \leftarrow R_3 - R_1$
> x계수(1행)가 1이므로, 2·3행의 x를 없애기 위해 1행을 뺌

**R2 계산:**
$$R_2 - R_1 = (1-1,\ 3-2,\ -6+4,\ 1-2) = (0,\ 1,\ -2,\ -1)$$

**R3 계산:**
$$R_3 - R_1 = (1-1,\ 2-2,\ -3+4,\ 4-2) = (0,\ 0,\ 1,\ 2)$$

$$\left[\begin{array}{ccc|c} 1 & 2 & -4 & 2 \\ 0 & 1 & -2 & -1 \\ 0 & 0 & 1 & 2 \end{array}\right]$$

---

### 2단계: 후진 대입법으로 해 계산

**3행에서 z 직접 읽기:**
$$z = 2$$

**2행에 z = 2 대입:**
$$y - 2z = -1 \implies y - 2(2) = -1 \implies y = 3$$

**1행에 y = 3, z = 2 대입:**
$$x + 2(3) - 4(2) = 2 \implies x + 6 - 8 = 2 \implies x = 4$$

---

## 방법 2: Gauss-Jordan 소거법

### 1단계: $R_2 \leftarrow R_2 - R_1$, $R_3 \leftarrow R_3 - R_1$
> (Gauss 소거법과 동일)

$$\left[\begin{array}{ccc|c} 1 & 2 & -4 & 2 \\ 0 & 1 & -2 & -1 \\ 0 & 0 & 1 & 2 \end{array}\right]$$

---

### 2단계: $R_1 \leftarrow R_1 - 2R_2$
> 1행의 y계수가 **2**이므로, 0으로 만들기 위해 2배한 R2를 뺌

**R1 계산:**
$$R_1 - 2R_2 = (1-0,\ 2-2,\ -4+4,\ 2+2) = (1,\ 0,\ 0,\ 4)$$

$$\left[\begin{array}{ccc|c} 1 & 0 & 0 & 4 \\ 0 & 1 & -2 & -1 \\ 0 & 0 & 1 & 2 \end{array}\right]$$

---

### 3단계: $R_2 \leftarrow R_2 + 2R_3$
> 2행의 z계수가 **-2**이므로, 0으로 만들기 위해 2배한 R3를 더함

**R2 계산:**
$$R_2 + 2R_3 = (0+0,\ 1+0,\ -2+2,\ -1+4) = (0,\ 1,\ 0,\ 3)$$

$$\left[\begin{array}{ccc|c} 1 & 0 & 0 & 4 \\ 0 & 1 & 0 & 3 \\ 0 & 0 & 1 & 2 \end{array}\right]$$

> 좌변이 단위행렬 → 해를 직접 읽어냄

---

## 두 방법 비교

| 구분 | Gauss 소거법 | Gauss-Jordan 소거법 |
|------|-------------|-------------------|
| 목표 행렬 | 상삼각행렬 | 단위행렬(RREF) |
| 해 구하는 방법 | 후진 대입법 필요 | 직접 읽어냄 |
| 행 연산 횟수 | 적음 | 많음 |
| 참조 페이지 | 49~50페이지 | 54~55페이지 |

---

## 정답

$$\boxed{x = 4,\quad y = 3,\quad z = 2}$$

In [ ]:
# 코드

[ Gauss 소거법 ]

[초기] 첨가행렬:
[[ 1.  2. -4.  2.]
 [ 1.  3. -6.  1.]
 [ 1.  2. -3.  4.]]

R2 ← R2 - 1×R1
[[ 1.  2. -4.  2.]
 [ 0.  1. -2. -1.]
 [ 1.  2. -3.  4.]]

R3 ← R3 - 1×R1
[[ 1.  2. -4.  2.]
 [ 0.  1. -2. -1.]
 [ 0.  0.  1.  2.]]

R3 ← R3 - 0×R2
[[ 1.  2. -4.  2.]
 [ 0.  1. -2. -1.]
 [ 0.  0.  1.  2.]]

[상삼각행렬 완성]:
[[ 1.  2. -4.  2.]
 [ 0.  1. -2. -1.]
 [ 0.  0.  1.  2.]]

x3 = 2
x2 = 3
x1 = 4

[ Gauss-Jordan 소거법 ]

[초기] 첨가행렬:
[[ 1.  2. -4.  2.]
 [ 1.  3. -6.  1.]
 [ 1.  2. -3.  4.]]

R2 ← R2 - 1×R1
[[ 1.  2. -4.  2.]
 [ 0.  1. -2. -1.]
 [ 1.  2. -3.  4.]]

R3 ← R3 - 1×R1
[[ 1.  2. -4.  2.]
 [ 0.  1. -2. -1.]
 [ 0.  0.  1.  2.]]

R1 ← R1 - 2×R2
[[ 1.  0.  0.  4.]
 [ 0.  1. -2. -1.]
 [ 0.  0.  1.  2.]]

R3 ← R3 - 0×R2
[[ 1.  0.  0.  4.]
 [ 0.  1. -2. -1.]
 [ 0.  0.  1.  2.]]

R1 ← R1 - 0×R3
[[ 1.  0.  0.  4.]
 [ 0.  1. -2. -1.]
 [ 0.  0.  1.  2.]]

R2 ← R2 - -2×R3
[[1. 0. 0. 4.]
 [0. 1. 0. 3.]
 [0. 0. 1. 2.]]

[단위행렬(RREF) 완성]:
[[1. 0. 0. 4.]
 [0. 1. 0. 3.]
 [0. 0. 1. 2.]]


[ numpy.li